//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.4
//
// <auto-generated>
//
// Generated from file `Calculator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.fiberhome.calculator.ice;

/** @hidden */
public class _ICalculatorPrxI extends com.zeroc.Ice._ObjectPrxI implements ICalculatorPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
